---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_user: root
      bridge_if: "wlp3s0"
    sno1:
      ansible_host: 192.168.1.100
      ansible_user: core
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      hostname: sno1
      interface: enp0s3
      mac_addr: "52:54:00:aa:bb:cc"
      ip: 192.168.1.100
      cidr: 192.168.1.0/24
      raw_path: "/root/VirtualBox VMs/sno1/sno1.raw"
      iso_path: "../deployment/agent.x86_64.iso"
      dns: 192.168.1.1
      gateway: 192.168.1.1

