---
# roles/sno_install/tasks/check_node_ready.yaml

- name: Wait until cluster version becomes Available=True
  shell: |
    oc get clusterversion version -o jsonpath="{.status.conditions[?(@.type=='Available')].status}" --kubeconfig ../deployment/auth/kubeconfig
  register: result
  retries: 60
  delay: 60
  until: result.stdout == "True"

- name: Wait for all cluster operators to be available
  shell: |
    oc get co -o json --kubeconfig ../deployment/auth/kubeconfig | jq -r '.items[] | select(.status.conditions[] | select(.type=="Available").status != "True") | .metadata.name'
  register: co_check
  retries: 60
  delay: 60
  until: co_check.stdout_lines | length == 0

- name: Set backup_path
  set_fact:
    backup_path: "../deployment/previous-run/{{ timestamp }}"

- name: Backup install log files from deployment to backup
  copy:
    src: "../deployment/{{ item }}"
    dest: "{{ backup_path }}/{{ item }}"
    remote_src: true
    force: true
  loop:
    - .openshift_install.log
    - .openshift_install_state.json

- name: Show oc login command
  shell: |
    oc login -u kubeadmin -p $(cat ../deployment/auth/kubeadmin-password) \
      https://api.sno-cluster.test:6443 --insecure-skip-tls-verify --kubeconfig ../deployment/auth/kubeconfig

# 必要なら終了タイマーや通知は最後に
- name: (Optional) 終了タイマー呼び出し
  import_role:
    name: common

