---
# roles/sno_install/tasks/configure_hypervisor_access.yaml

- name: Create /root/.ssh/config
  copy:
    dest: /root/.ssh/config
    content: |
      Host sno1
          Hostname              {{ hostvars['sno1'].ansible_host }}
          User                  core

      Host *
          StrictHostKeyChecking no
          UserKnownHostsFile    /dev/null
          LogLevel              QUIET
          CanonicalizeHostname yes
          CanonicalDomains local
          CanonicalizeFallbackLocal yes
    owner: root
    group: root
    mode: '0644'

- name: Get last octet reversed IP
  set_fact:
    rev_ip: "{{ hostvars['sno1'].ansible_host.split('.') | reverse | join('.') }}"

- name: Ensure systemd-resolved override directory exists
  file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    mode: '0755'

- name: Configure systemd-resolved to forward .apps.{{ sno_cluster_name }}.{{ base_domain }} to 127.0.0.1
  copy:
    dest: /etc/systemd/resolved.conf.d/dnsmasq-openshift.conf
    content: |
      [Resolve]
      DNS=127.0.0.1
      Domains=~apps.{{ sno_cluster_name }}.{{ base_domain }} ~{{ sno_cluster_name }}.{{ base_domain }} ~{{ rev_ip }}.in-addr.arpa.

    mode: '0644'

- name: Ensure dnsmasq.d directory exists
  file:
    path: /etc/dnsmasq.d
    state: directory
    mode: '0755'

- name: Add dnsmasq rule for .apps.{{ sno_cluster_name }}.{{ base_domain }} and related entries
  copy:
    dest: /etc/dnsmasq.d/openshift.conf
    content: |
      address=/{{ sno_cluster_name }}.{{ base_domain }} /{{ hostvars['sno1'].ansible_host }}
      address=/.apps.{{ sno_cluster_name }}.{{ base_domain }}/{{ hostvars['sno1'].ansible_host }}

      ptr-record={{ rev_ip }}.in-addr.arpa,{{ hostvars['sno1'].hostname }}.{{ sno_cluster_name }}.{{ base_domain }}
      ptr-record={{ rev_ip }}.in-addr.arpa,api.{{ sno_cluster_name }}.{{ base_domain }}
      ptr-record={{ rev_ip }}.in-addr.arpa,api-int.{{ sno_cluster_name }}.{{ base_domain }}
      ptr-record={{ rev_ip }}.in-addr.arpa,oauth-openshift.apps.{{ sno_cluster_name }}.{{ base_domain }}
      ptr-record={{ rev_ip }}.in-addr.arpa,console-openshift-console.apps.{{ sno_cluster_name }}.{{ base_domain }}

      no-resolv
    mode: '0644'

- name: Enable and restart dnsmasq
  systemd:
    name: dnsmasq
    enabled: yes
    state: restarted

- name: Restart systemd-resolved to apply domain forwarding
  systemd:
    name: systemd-resolved
    state: restarted

# 必要であれば終了タイマーや通知はここに（推奨はimport_role形式）
- name: (Optional) 終了タイマー呼び出し
  import_role:
    name: common

