---
- name: "Record start time for {{ play_description | default(playbook_dir) }}"
  set_fact:
    this_start: "{{ lookup('pipe','date +%s') | int }}"
  run_once: true

- name: "Display start time in Asia/Tokyo"
  debug:
    msg: >-
      {{
        lookup(
          'pipe',
          "TZ=Asia/Tokyo date -d @"
          ~ this_start|string
          ~ " '+%Y-%m-%d %H:%M:%S %Z'"
        )
      }}
  run_once: true
