---
- name: Generate timestamp variable and save to file
  set_fact:
    timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M-%S') }}"
  delegate_to: localhost

- name: Save timestamp to file
  copy:
    content: "{{ timestamp }}"
    dest: /tmp/deploy_timestamp.txt
  delegate_to: localhost

